services:
  users-service:
    build: ./ridenow/users-service
    container_name: users-service
    ports:
      - "8001:8001"
    volumes:
      - ./ridenow/users-service/data:/app/data

  pricing-service:
    build: ./ridenow/pricing-service
    container_name: pricing-service
    ports:
      - "8002:8002"
    volumes:
      - ./ridenow/pricing-service/data:/app/data

  payment-service:
    build: ./ridenow/payment-service
    container_name: payment-service
    ports:
      - "8003:8003"
    volumes:
      - ./ridenow/payment-service/data:/app/data

  ride-service:
    build: ./ridenow/ride-service
    container_name: ride-service
    ports:
      - "8004:8004"
    depends_on:
      - users-service
      - pricing-service
      - payment-service
    volumes:
      - ./ridenow/ride-service/data:/app/data
